services:
  server:
    build:
      context: ../../
      dockerfile: cmd/server/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - app_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - app_network
    depends_on:
      - server

networks:
  app_network:
    driver: bridge